export const FETCH_BOARDS_REQUEST = "FETCH_BOARDS_REQUEST";
export const FETCH_BOARDS_SUCCESS = "FETCH_BOARDS_SUCCESS";
export const CREATE_BOARD_REQUEST = "CREATE_BOARD_REQUEST";
export const CREATE_BOARD_SUCCESS = "CREATE_BOARD_SUCCESS";
export const FETCH_BOARD_SUCCESS = "FETCH_BOARD_SUCCESS";

// LISTS

export const CREATE_LIST_SUCCESS = "CREATE_LIST_SUCCESS";
export const UPDATE_LIST_SUCCESS = "UPDATE_LIST_SUCCESS";

// CARDS

export const CREATE_CARD_SUCCESS = "CREATE_CARD_SUCCESS";
export const FETCH_CARD_SUCCESS = "FETCH_CARD_SUCCESS";
